### ISSUE TITLE
chainer-gan-lib/common/evaluation.py", line 142: 'numpy.ndarray' object has no attribute 'get'

### ISSUE THREAD

**Issue by mingxiaoh** [pfnet-research/chainer-gan-lib#15]
Hello, I tried "python train.py --gpu -1 --algorithm dcgan --out result_dcgan " with chainerv5.0.0a1&iDeep, I saw following error:
File "/home/mingxiao/Documents/chainer-gan-lib/common/evaluation.py", line 175, in evaluation
    mean, cov = get_mean_cov(model, np.asarray(xs).reshape((-1, 3, h, w)))
  File "/home/mingxiao/Documents/chainer-gan-lib/common/evaluation.py", line 142, in get_mean_cov
    mean = xp.mean(ys, axis=0).get()
AttributeError: 'numpy.ndarray' object has no attribute 'get'

Have you ever seen this before? Thanks in advance.

**Comment by takerum** [comment]
Hi, I create pull request to fix this issue : #16 
Could you check whether it works?

**Comment by mingxiaoh** [comment]
thanks, we will try it later.

**Comment by takerum** [comment]
It seems like you are running on the master branch.
Please checkout `takerum-patch-1` branch then run the code.

**Comment by mingxiaoh** [comment]
oh, sorry, I forgot to switch the branch, I will try that branch, thanks.

**Comment by mingxiaoh** [comment]
it works now, thanks.
